<?php

/**
 * AistLocale (http://mateuszsitek.com/projects/aist-locale)
 *
 * @link      http://github.com/ma-si/aist-locale for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Aist Internet Technologies (http://aist.pl) All rights reserved.
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause
 */

return [
    'translator' => [
        'plural_rules' => [
            'ach' => ['name' => 'Acholi', 'rule' => 'nplurals=2; plural=(n > 1);'],
            'af' => ['name' => 'Afrikaans', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ak' => ['name' => 'Akan', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'am' => ['name' => 'Amharic', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'an' => ['name' => 'Aragonese', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'anp' => ['name' => 'Angika', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ar' => ['name' => 'Arabic [1]', 'rule' => 'nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5)'],
            'arn' => ['name' => 'Mapudungun', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'as' => ['name' => 'Assamese', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ast' => ['name' => 'Asturian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ay' => ['name' => 'Aymará', 'rule' => 'nplurals=1; plural=0'],
            'az' => ['name' => 'Azerbaijani', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'be' => ['name' => 'Belarusian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'bg' => ['name' => 'Bulgarian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'bn' => ['name' => 'Bengali', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'bo' => ['name' => 'Tibetan', 'rule' => 'nplurals=1; plural=0'],
            'br' => ['name' => 'Breton', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'brx' => ['name' => 'Bodo', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'bs' => ['name' => 'Bosnian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'ca' => ['name' => 'Catalan', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'cgg' => ['name' => 'Chiga', 'rule' => 'nplurals=1; plural=0'],
            'cs' => ['name' => 'Czech', 'rule' => 'nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2'],
            'csb' => ['name' => 'Kashubian', 'rule' => 'nplurals=3; plural=(n==1) ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2'],
            'cy' => ['name' => 'Welsh', 'rule' => 'nplurals=4; plural=(n==1) ? 0 : (n==2) ? 1 : (n != 8 && n != 11) ? 2 : 3'],
            'da' => ['name' => 'Danish', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'de' => ['name' => 'German', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'doi' => ['name' => 'Dogri', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'dz' => ['name' => 'Dzongkha', 'rule' => 'nplurals=1; plural=0'],
            'el' => ['name' => 'Greek', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'en' => ['name' => 'English', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'eo' => ['name' => 'Esperanto', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'es' => ['name' => 'Spanish', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'es_AR' => ['name' => 'Argentinean Spanish', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'et' => ['name' => 'Estonian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'eu' => ['name' => 'Basque', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'fa' => ['name' => 'Persian', 'rule' => 'nplurals=1; plural=0'],
            'ff' => ['name' => 'Fulah', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'fi' => ['name' => 'Finnish', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'fil' => ['name' => 'Filipino', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'fo' => ['name' => 'Faroese', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'fr' => ['name' => 'French', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'fur' => ['name' => 'Friulian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'fy' => ['name' => 'Frisian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ga' => ['name' => 'Irish', 'rule' => 'nplurals=5; plural=(n==1) ? 0 : n==2 ? 1 : n<7 ? 2 : n<11 ? 3 : 4'],
            'gd' => ['name' => 'Scottish Gaelic', 'rule' => 'nplurals=4; plural=(n==1 || n==11) ? 0 : (n==2 || n==12) ? 1 : (n > 2 && n < 20) ? 2 : 3'],
            'gl' => ['name' => 'Galician', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'gu' => ['name' => 'Gujarati', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'gun' => ['name' => 'Gun', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'ha' => ['name' => 'Hausa', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'he' => ['name' => 'Hebrew', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'hi' => ['name' => 'Hindi', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'hne' => ['name' => 'Chhattisgarhi', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'hy' => ['name' => 'Armenian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'hr' => ['name' => 'Croatian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'hu' => ['name' => 'Hungarian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ia' => ['name' => 'Interlingua', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'id' => ['name' => 'Indonesian', 'rule' => 'nplurals=1; plural=0'],
            'is' => ['name' => 'Icelandic', 'rule' => 'nplurals=2; plural=(n%10!=1 || n%100==11)'],
            'it' => ['name' => 'Italian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ja' => ['name' => 'Japanese', 'rule' => 'nplurals=1; plural=0'],
            'jbo' => ['name' => 'Lojban', 'rule' => 'nplurals=1; plural=0'],
            'jv' => ['name' => 'Javanese', 'rule' => 'nplurals=2; plural=(n != 0)'],
            'ka' => ['name' => 'Georgian', 'rule' => 'nplurals=1; plural=0'],
            'kk' => ['name' => 'Kazakh', 'rule' => 'nplurals=1; plural=0'],
            'kl' => ['name' => 'Greenlandic', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'km' => ['name' => 'Khmer', 'rule' => 'nplurals=1; plural=0'],
            'kn' => ['name' => 'Kannada', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ko' => ['name' => 'Korean', 'rule' => 'nplurals=1; plural=0'],
            'ku' => ['name' => 'Kurdish', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'kw' => ['name' => 'Cornish', 'rule' => 'nplurals=4; plural=(n==1) ? 0 : (n==2) ? 1 : (n == 3) ? 2 : 3'],
            'ky' => ['name' => 'Kyrgyz', 'rule' => 'nplurals=1; plural=0'],
            'lb' => ['name' => 'Letzeburgesch', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ln' => ['name' => 'Lingala', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'lo' => ['name' => 'Lao', 'rule' => 'nplurals=1; plural=0'],
            'lt' => ['name' => 'Lithuanian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'lv' => ['name' => 'Latvian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2)'],
            'mai' => ['name' => 'Maithili', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'mfe' => ['name' => 'Mauritian Creole', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'mg' => ['name' => 'Malagasy', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'mi' => ['name' => 'Maori', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'mk' => ['name' => 'Macedonian', 'rule' => 'nplurals=2; plural= n==1 || n%10==1 ? 0 : 1;'], //Can’t be correct needs a 2 somewhere
            'ml' => ['name' => 'Malayalam', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'mn' => ['name' => 'Mongolian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'mni' => ['name' => 'Manipuri', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'mnk' => ['name' => 'Mandinka', 'rule' => 'nplurals=3; plural=(n==0 ? 0 : n==1 ? 1 : 2)'],
            'mr' => ['name' => 'Marathi', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ms' => ['name' => 'Malay', 'rule' => 'nplurals=1; plural=0'],
            'mt' => ['name' => 'Maltese', 'rule' => 'nplurals=4; plural=(n==1 ? 0 : n==0 || ( n%100>1 && n%100<11) ? 1 : (n%100>10 && n%100<20 ) ? 2 : 3)'],
            'my' => ['name' => 'Burmese', 'rule' => 'nplurals=1; plural=0'],
            'nah' => ['name' => 'Nahuatl', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'nap' => ['name' => 'Neapolitan', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'nb' => ['name' => 'Norwegian Bokmal', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ne' => ['name' => 'Nepali', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'nl' => ['name' => 'Dutch', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'se' => ['name' => 'Northern Sami', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'nn' => ['name' => 'Norwegian Nynorsk', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'no' => ['name' => 'Norwegian (old code)', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'nso' => ['name' => 'Northern Sotho', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'oc' => ['name' => 'Occitan', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'or' => ['name' => 'Oriya', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ps' => ['name' => 'Pashto', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'pa' => ['name' => 'Punjabi', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'pap' => ['name' => 'Papiamento', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'pl' => ['name' => 'Polish', 'rule' => 'nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'pms' => ['name' => 'Piemontese', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'pt' => ['name' => 'Portuguese', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'pt_BR' => ['name' => 'Brazilian Portuguese', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'rm' => ['name' => 'Romansh', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ro' => ['name' => 'Romanian', 'rule' => 'nplurals=3; plural=(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2)'],
            'ru' => ['name' => 'Russian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'rw' => ['name' => 'Kinyarwanda', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'sah' => ['name' => 'Yakut', 'rule' => 'nplurals=1; plural=0'],
            'sat' => ['name' => 'Santali', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'sco' => ['name' => 'Scots', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'sd' => ['name' => 'Sindhi', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'si' => ['name' => 'Sinhala', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'sk' => ['name' => 'Slovak', 'rule' => 'nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2'],
            'sl' => ['name' => 'Slovenian', 'rule' => 'nplurals=4; plural=(n%100==1 ? 1 : n%100==2 ? 2 : n%100==3 || n%100==4 ? 3 : 0)'],
            'so' => ['name' => 'Somali', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'son' => ['name' => 'Songhay', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'sq' => ['name' => 'Albanian', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'sr' => ['name' => 'Serbian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'su' => ['name' => 'Sundanese', 'rule' => 'nplurals=1; plural=0'],
            'sw' => ['name' => 'Swahili', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'sv' => ['name' => 'Swedish', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'ta' => ['name' => 'Tamil', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'te' => ['name' => 'Telugu', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'tg' => ['name' => 'Tajik', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'ti' => ['name' => 'Tigrinya', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'th' => ['name' => 'Thai', 'rule' => 'nplurals=1; plural=0'],
            'tk' => ['name' => 'Turkmen', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'tr' => ['name' => 'Turkish', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'tt' => ['name' => 'Tatar', 'rule' => 'nplurals=1; plural=0'],
            'ug' => ['name' => 'Uyghur', 'rule' => 'nplurals=1; plural=0'],
            'uk' => ['name' => 'Ukrainian', 'rule' => 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)'],
            'ur' => ['name' => 'Urdu', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'uz' => ['name' => 'Uzbek', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'vi' => ['name' => 'Vietnamese', 'rule' => 'nplurals=1; plural=0'],
            'wa' => ['name' => 'Walloon', 'rule' => 'nplurals=2; plural=(n > 1)'],
            'wo' => ['name' => 'Wolof', 'rule' => 'nplurals=1; plural=0'],
            'yo' => ['name' => 'Yoruba', 'rule' => 'nplurals=2; plural=(n != 1)'],
            'zh' => ['name' => 'Chinese [2]', 'rule' => 'nplurals=1; plural=0'],
            'zh' => ['name' => 'Chinese [3]', 'rule' => 'nplurals=2; plural=(n > 1)'],
        ],
    ],
];
